
################################################################
# extra files to be added to distribution
################################################################

EXTRA_DIST =	\
			analysis/out-overlap.md \
			analysis/out-overlap/reproduce.py \
			conda.txt \
			api-documentation.md \
			build-api.sh \
			check-api.py \
			doxygen.cfg \
			doxygen/mainpage.md \
			doxygen/header.html \
			doxygen/footer.html \
			doxygen/intarna.css \
			latex-deps/adjcalc.sty \
			latex-deps/adjustbox.sty \
			latex-deps/collectbox.sty \
			latex-deps/tc-pgf.def \
			latex-deps/tocloft.sty \
			latex-deps/trimclip.sty \
			latex-deps/xtab.sty
