
################################################################
# extra files to be added to distribution
################################################################

EXTRA_DIST =	\
			analysis/out-overlap.md \
			analysis/out-overlap/reproduce.py \
			conda.txt \
			kinetic-seed-extension.md \
			benchmark-kix.py \
			kix-benchmark-20261005.json \
			handson/README.md \
			handson/fhlA.fasta \
			handson/OxyS.fasta \
			handson/phoB.fasta \
			handson/GcvB.fasta \
			handson/ilvE.fasta \
			handson/GcvB.ST.fasta \
			recursions/IntaRNAsnap.PredictorSeedExtensionKinetic.svg \
			doxygen.cfg \
			latex-deps/adjcalc.sty \
			latex-deps/adjustbox.sty \
			latex-deps/collectbox.sty \
			latex-deps/tc-pgf.def \
			latex-deps/tocloft.sty \
			latex-deps/trimclip.sty \
			latex-deps/xtab.sty
